# Makefile.ci holds make directives called by the CI jobs for this repo.

populate-federation-gopath:
	./scripts/populate-federation-gopath.sh

.ONESHELL:
unit: populate-federation-gopath
	echo "OK"

.ONESHELL:
vet: populate-federation-gopath
	echo "OK"

# This target was effectively removed in 0.0.8
.ONESHELL:
managed-e2e: populate-federation-gopath
	echo "OK"

olm-e2e: populate-federation-gopath
	echo "OK"
